/// Token kinds needed for the first script-style `println()` programs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TokenType {
    Can,
    Cannot,
    Effect,
    Identifier,
    InterpolationStart,
    String,
    StringEnd,
    StringStart,
    StringText,
    False,
    Fun,
    Native,
    Not,
    True,
    Use,
    Colon,
    Comma,
    DoubleColon,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    Semicolon,
    Test,
    Unexpected,
    EndOfFile,
}
