[package]
name = "ocelot-engine"
version = "0.1.1"
edition = "2024"
description = "Language pipeline orchestration for the ocelot project"
license = "MIT"
repository = "https://github.com/manuel-woelker/ocelot"

[dependencies]
ocelot-ast = { path = "../ast", version = "0.1.1" }
ocelot-base = { path = "../base", version = "0.1.1" }
ocelot-interpreter = { path = "../interpreter", version = "0.1.1" }
ocelot-pal = { path = "../pal", version = "0.1.1" }
ocelot-parser = { path = "../parser", version = "0.1.1" }

[dev-dependencies]
expect-test = "1.5.1"
