[package]
name = "ocelot-engine"
version = "0.1.1"
edition = "2024"
description = "Language pipeline orchestration for the ocelot project"
license = "MIT"
repository = "https://github.com/manuel-woelker/ocelot"

[dependencies]
ocelot-ast = { path = "../ast", version = "0.1.1" }
ocelot-base = { path = "../base", version = "0.1.1" }
ocelot-interpreter = { path = "../interpreter", version = "0.1.1" }
ocelot-parser = { path = "../parser", version = "0.1.1" }
ocelot-resolver = { path = "../resolver", version = "0.1.1" }
