[package]
name = "ocelot-formatter"
version = "0.1.2"
edition = "2024"
description = "Formatter for the ocelot project"
license = "MIT"
repository = "https://github.com/manuel-woelker/ocelot"

[dependencies]
ocelot-ast = { path = "../ast", version = "0.1.2" }

[dev-dependencies]
ocelot-base = { path = "../base", version = "0.1.2" }
ocelot-parser = { path = "../parser", version = "0.1.2" }

