[package]
name = "ocelot-spec-validation"
version = "0.1.1"
edition = "2024"
description = "Specification example validation for the ocelot project"
license = "MIT"
repository = "https://github.com/manuel-woelker/ocelot"

[dependencies]
ocelot-base = { path = "../base", version = "0.1.1" }
ocelot-engine = { path = "../engine", version = "0.1.1" }
ocelot-pal = { path = "../pal", version = "0.1.1" }

[dev-dependencies]
expect-test = { workspace = true }
