<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>Ocelot</string>
  <key>scopeName</key>
  <string>source.ocelot</string>
  <key>fileTypes</key>
  <array>
    <string>ocelot</string>
  </array>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#comments</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#strings</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#booleans</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#keywords</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#builtins</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#identifiers</string>
    </dict>
    <dict>
      <key>include</key>
      <string>#punctuation</string>
    </dict>
  </array>
  <key>repository</key>
  <dict>
    <key>booleans</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b(?:true|false)\b</string>
          <key>name</key>
          <string>constant.language.boolean.ocelot</string>
        </dict>
      </array>
    </dict>
    <key>builtins</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b(?:assert_eq|println)\b(?=\s*\()</string>
          <key>name</key>
          <string>support.function.builtin.ocelot</string>
        </dict>
      </array>
    </dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>/\*</string>
          <key>end</key>
          <string>\*/</string>
          <key>name</key>
          <string>comment.block.ocelot</string>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#comments</string>
            </dict>
          </array>
        </dict>
        <dict>
          <key>match</key>
          <string>//.*$</string>
          <key>name</key>
          <string>comment.line.double-slash.ocelot</string>
        </dict>
      </array>
    </dict>
    <key>identifiers</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b[_[:alpha:]][_[:alnum:]]*\b</string>
          <key>name</key>
          <string>variable.other.readwrite.ocelot</string>
        </dict>
      </array>
    </dict>
    <key>keywords</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\btest\b</string>
          <key>name</key>
          <string>keyword.declaration.ocelot</string>
        </dict>
      </array>
    </dict>
    <key>punctuation</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>[(){};,]</string>
          <key>name</key>
          <string>punctuation.separator.ocelot</string>
        </dict>
      </array>
    </dict>
    <key>strings</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>"</string>
          <key>beginCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.begin.ocelot</string>
            </dict>
          </dict>
          <key>end</key>
          <string>"</string>
          <key>endCaptures</key>
          <dict>
            <key>0</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.string.end.ocelot</string>
            </dict>
          </dict>
          <key>name</key>
          <string>string.quoted.double.ocelot</string>
        </dict>
      </array>
    </dict>
  </dict>
  <key>uuid</key>
  <string>8CC7B61E-65B2-4A88-9B49-655B9836F61F</string>
</dict>
</plist>
